/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 macbook.gltf
*/

import React, { useEffect, useRef, useState } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  Float,
  useTexture,
} from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
function Rig() {
  return useFrame((state, delta) => {
    easing.damp3(
      state.camera.position,
      [0.5 + state.mouse.x, 0.15 + state.mouse.y / 2, 4],
      0.5,
      delta
    );
  });
}

export function Model(props) {
  const { nodes, materials } = useGLTF("/macbook.gltf");
  let screenStart = 0;

  const myGroup = useRef();

  const colorTexture = useTexture("./textures/SCR-20230306-nao.png");

  return (
    <PerspectiveCamera position={[-0.5, -1.2, 0]}>
      <Float speed={0.5}>
        <group
          {...props}
          dispose={null}
          scale={1.45}
          position={[-1, 0, 0]}
          rotation={[0.15, 1, -0.2]}
        >
          <mesh
            geometry={nodes.Cube001.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Cube001_2.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Cube001_3.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Cube001_4.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Cube001_5.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials["Material.011"]}
            position={[-1.45, 0.09, -0.57]}
          />
          <group position={[0, 0.1, -1.01]} rotation={[0, 0, 0]} ref={myGroup}>
            <mesh
              geometry={nodes.Cube017.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              geometry={nodes.Cube017_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Cube017_2.geometry}
              material={materials["Material.006"]}
            />
            <mesh
              geometry={nodes.Cube017_3.geometry}
              material={materials["Material.005"]}
            />
            <mesh
              geometry={nodes.Cube017_4.geometry}
              material={colorTexture}
              map
            />
            <mesh
              geometry={nodes.Curve.geometry}
              material={materials["Material.017"]}
              position={[-0.03, 0.62, 1.02]}
              rotation={[Math.PI, 0, Math.PI]}
              scale={[32.94, 32.94, 33.49]}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials["Material.010"]}
            position={[-1.49, 0.09, -0.76]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={-0.01}
          />
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.Cylinder_2.geometry}
            material={materials["Material.014"]}
          />
        </group>
        {/* <Rig /> */}
      </Float>
    </PerspectiveCamera>
  );
}

useGLTF.preload("/macbook.gltf");
